### ISSUE TITLE
Create a script to add templates to new files (and also for older files)

### ISSUE THREAD

**Issue by SituesmonpainJetejetterai** [SituesmonpainJetejetterai/workstation-dotfiles#26]
Create a script that will add a template to a new file (created either by `vim` or by `touch`).

The contents for various filetypes will be:

## `shell`
```
#!/bin/sh

##############################################################
# Author: "$(git config --list | grep "user.name" | sed "s/.*=//")"
# Name: "$(basename "$(test -L "$1" && readlink "$1" || printf "\n%s" "$1")")"
# Source: "$(basename "$(git remote show -n origin)" | sed -n "1p" | sed "s/.git//")"
##############################################################
```

## `python`
```
#!/bin/python3

##############################################################
# Author: "$(git config --list | grep "user.name" | sed "s/.*=//")"
# Name: "$(basename "$(test -L "$1" && readlink "$1" || printf "\n%s" "$1")")"
# Source: "$(basename "$(git remote show -n origin)" | sed -n "1p" | sed "s/.git//")"
##############################################################
```

## `markdown`
```
##############################################################
# Author: "$(git config --list | grep "user.name" | sed "s/.*=//")"
# Name: "$(basename "$(test -L "$1" && readlink "$1" || printf "\n%s" "$1")")"
# Source: "$(basename "$(git remote show -n origin)" | sed -n "1p" | sed "s/.git//")"
# Time: "$(date -u)"
##############################################################
```

# Issues:
- The part about the date is variable and needs to be reviewed.
- Remove the automatic `shebang` rule from `vim`.

**Comment by jetejetteraiASAP** [comment]
Links:
- https://unix.stackexchange.com/questions/20903/inserting-text-at-the-beginning-of-a-file-with-sed-via-the-terminal-in-linux
- https://stackoverflow.com/questions/148451/how-to-use-sed-to-replace-only-the-first-occurrence-in-a-file
- https://stackoverflow.com/questions/9964823/how-to-check-if-a-file-is-empty-in-bash
- https://www.unix.com/shell-programming-and-scripting/154513-sed-insert-text-first-line-empty-file.html

**Comment by jetejetteraiASAP** [comment]
Another one for `ed`: https://unix.stackexchange.com/a/20579

**Comment by SituesmonpainJetejetterai** [comment]
The problem with `sed` or `ed` is that these will essentially create another file with the template on top and then the rest of the content. This will not work for symlinked files (acc. to me). For now, I'll give this a pass.
